version: '3.4'

networks:
  charity_network:
    external: true
    name: charity-network

services:
  charityappbackend:
    image: charityappbackend:latest
    build:
      context: .
      dockerfile: CharityAppBackend/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__MySQLConnection=Server=mysql-charity-hoangtrinh;Port=3306;Database=charity;Uid=root;Pwd=123456;
    volumes:
      - ./:/charitybackendapi
    networks:
      - charity_network
  cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - charity_network
volumes:
  charity-mysql-data:

