version: '3.4'

services:
  charityappbackend:
    image: charityappbackend:latest
    build:
      context: .
      dockerfile: CharityAppBackend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__MySQLConnection=Server=db;Port=3306;Database=charity;Uid=root;Pwd=secret;
    volumes:
      - ./:/charitybackendapi
  db:
    image: mysql:8.0
    ports:
      - "3666:3306"
    volumes:
      - charity-mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: charity
  cache:
    image: redis
    ports:
      - "6379:6379"
volumes:
  charity-mysql-data:

