using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace Base
{
    public class BLBase : IBLBase
    {
        public string CreatePasswordHash(string password, string salt)
        {
            byte[] passwordBytes = Encoding.UTF8.GetBytes(password);
            byte[] saltBytes = Encoding.UTF8.GetBytes(salt);
            using var hmac = new System.Security.Cryptography.HMACSHA512(saltBytes);
            var hashBytes = hmac.ComputeHash(passwordBytes);
            return Convert.ToBase64String(hashBytes);
        }

        public string GenerateSalt(int length = 32)
        {
            // Create a new instance of the RNGCryptoServiceProvider
            RandomNumberGenerator rng = RandomNumberGenerator.Create();

            // Create a byte array to store the salt value
            byte[] saltBytes = new byte[length];

            // Fill the byte array with random values generated by the RNGCryptoServiceProvider
            rng.GetBytes(saltBytes);

            // Convert the byte array to a string and return it
            return Convert.ToBase64String(saltBytes);
        }
    }
}
