using FluentEmail.Core;
using FluentEmail.Razor;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;
using Newtonsoft.Json.Schema.Generation;
using System.Dynamic;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
public static class CharityUtil
{
    public static string CreatePasswordHash(string password, string salt)
    {
        byte[] passwordBytes = Encoding.UTF8.GetBytes(password);
        byte[] saltBytes = Encoding.UTF8.GetBytes(salt);
        using var hmac = new HMACSHA512(saltBytes);
        var hashBytes = hmac.ComputeHash(passwordBytes);
        return Convert.ToBase64String(hashBytes);
    }

    public static string GenerateSalt(int length = 32)
    {
        // Create a new instance of the RNGCryptoServiceProvider
        RandomNumberGenerator rng = RandomNumberGenerator.Create();

        // Create a byte array to store the salt value
        byte[] saltBytes = new byte[length];

        // Fill the byte array with random values generated by the RNGCryptoServiceProvider
        rng.GetBytes(saltBytes);

        // Convert the byte array to a string and return it
        return Convert.ToBase64String(saltBytes);
    }

    public static bool VerifyPasswordHash(string password, string hashPassword, string saltPassword)
    {
        var saltPasswordBytes = Encoding.UTF8.GetBytes(saltPassword);
        var hashPasswordBytes = Convert.FromBase64String(hashPassword);
        using (var hmac = new System.Security.Cryptography.HMACSHA512(saltPasswordBytes))
        {
            var computedHashBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(password));
            if (computedHashBytes == null || hashPasswordBytes == null || computedHashBytes.Length != hashPasswordBytes.Length)
            {
                return false;
            }
            for (int i = 0; i < computedHashBytes.Length; i++)
            {
                if (computedHashBytes[i] != hashPasswordBytes[i])
                {
                    return false;
                }
            }
            return true;
        }
    }

    public static async Task<bool> SendResetPasswordEmail(string email, string resetCode)
    {
        var senderEmail = "kienlevan2001@gmail.com";
        var senderName = "kien";

        var model = new { ResetCode = resetCode };
        //await Email
        //    .From(senderEmail, senderName)
        //    .To(email)
        //.Subject("Password Reset")
        //.UsingTemplate()    
        //.SendAsync();

        return true;
    }

    public static ExpandoObject ToExpando(object model)
    {
        if (model is ExpandoObject exp)
        {
            return exp;
        }

        IDictionary<string, object> expando = new ExpandoObject();
        foreach (var propertyDescriptor in model.GetType().GetTypeInfo().GetProperties())
        {
            var obj = propertyDescriptor.GetValue(model);

            if (obj != null && IsAnonymousType(obj.GetType()))
            {
                obj = ToExpando(obj);
            }

            expando.Add(propertyDescriptor.Name, obj);
        }

        return (ExpandoObject)expando;
    }

    private static bool IsAnonymousType(Type type)
    {
        bool hasCompilerGeneratedAttribute = type.GetTypeInfo()
            .GetCustomAttributes(typeof(CompilerGeneratedAttribute), false)
            .Any();

        bool nameContainsAnonymousType = type.FullName.Contains("AnonymousType");
        bool isAnonymousType = hasCompilerGeneratedAttribute && nameContainsAnonymousType;

        return isAnonymousType;
    }

    public static bool CanBeConverted<T>(object value) where T : class
    {
        var jsonData = JsonConvert.SerializeObject(value);
        var generator = new JSchemaGenerator();
        var parsedSchema = generator.Generate(typeof(T));
        var jObject = JObject.Parse(jsonData);
        return jObject.IsValid(parsedSchema);
    }

    public static T ConvertToType<T>(object value) where T : class
    {
        var jsonData = JsonConvert.SerializeObject(value);
        if (jsonData.Contains("\"Id\":null,"))
        {
            jsonData = jsonData.Replace("\"Id\":null,", String.Empty);
        }
        return JsonConvert.DeserializeObject<T>(jsonData);
    }
}
